include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore
    library_private_types_in_public_api: ignore
    must_be_immutable: ignore
    prefer_interpolation_to_compose_strings: ignore
