import 'package:hive/hive.dart';

part 'ride.g.dart'; //Autogenerated with flutter packages pub run build_runner build

@HiveType(typeId: 0) 
class Ride {
  @HiveField(0) 
  final int driverId;

  @HiveField(1) 
  final int commanderId;

  const Ride({
    required this.driverId,
    required this.commanderId,
  });

  Map<String, dynamic> toJson() {
    return {
      'driver': driverId,
      'commander': commanderId,
    };
  }
}
