import 'package:hive/hive.dart';

part 'ride.g.dart'; //Autogenerated with flutter packages pub run build_runner build

@HiveType(typeId: 0) 
class Ride {
  @HiveField(0) 
  final int driverId;

  @HiveField(1) 
  final int commanderId;

  @HiveField(2)
  final DateTime? rideDate = DateTime.now();

  @HiveField(3)
  final String? rideDescription = "";

  Ride({
    required this.driverId,
    required this.commanderId,
    //required this.rideDate,
    //required this.rideDescription
  });

  Map<String, dynamic> toJson() {
    return {
      'driver': driverId,
      'commander': commanderId,
    };
  }
}
